insert into roles (id, name) values (1, 'Administrator');
insert into users (id, username, password, role_id) values(1, 'edwin', '123', 1);
insert into inventaries (id, name, category, quantity) values (1, 'Keyboard', 'Tech', 5);
insert into inventaries (id, name, category, quantity) values (2, 'Monitor', 'Tech', 10);
insert into inventaries (id, name, category, quantity) values (3, 'Desk Chair', 'Furniture', 15);
insert into inventaries (id, name, category, quantity) values (4, 'Notebook', 'Stationery', 20);
insert into inventaries (id, name, category, quantity) values (5, 'Tablet', 'Tech', 25);
insert into inventaries (id, name, category, quantity) values (6, 'Pen', 'Stationery', 30);
insert into inventaries (id, name, category, quantity) values (7, 'Desk Lamp', 'Furniture', 35);
insert into inventaries (id, name, category, quantity) values (8, 'Webcam', 'Tech', 40);
insert into inventaries (id, name, category, quantity) values (9, 'Printer', 'Tech', 45);
insert into inventaries (id, name, category, quantity) values (10, 'Smartphone', 'Tech', 50);
insert into inventaries (id, name, category, quantity) values (11, 'Headphones', 'Tech', 55);
insert into inventaries (id, name, category, quantity) values (12, 'Laptop', 'Tech', 60);
insert into inventaries (id, name, category, quantity) values (13, 'External Hard Drive', 'Tech', 65);
insert into inventaries (id, name, category, quantity) values (14, 'Coffee Maker', 'Appliances', 70);
insert into inventaries (id, name, category, quantity) values (15, 'Water Bottle', 'Kitchenware', 75);
insert into inventaries (id, name, category, quantity) values (16, 'Router', 'Tech', 80);
insert into inventaries (id, name, category, quantity) values (17, 'Projector', 'Tech', 85);
insert into inventaries (id, name, category, quantity) values (18, 'Paper Ream', 'Stationery', 90);
insert into inventaries (id, name, category, quantity) values (19, 'Scanner', 'Tech', 95);
insert into inventaries (id, name, category, quantity) values (20, 'Mouse', 'Tech', 100);
insert into inventaries (id, name, category, quantity) values (21, 'Keyboard', 'Tech', 105);
insert into inventaries (id, name, category, quantity) values (22, 'Monitor', 'Tech', 110);
insert into inventaries (id, name, category, quantity) values (23, 'Desk Chair', 'Furniture', 115);
insert into inventaries (id, name, category, quantity) values (24, 'Notebook', 'Stationery', 120);
insert into inventaries (id, name, category, quantity) values (25, 'Tablet', 'Tech', 125);
insert into inventaries (id, name, category, quantity) values (26, 'Pen', 'Stationery', 130);
insert into inventaries (id, name, category, quantity) values (27, 'Desk Lamp', 'Furniture', 135);
insert into inventaries (id, name, category, quantity) values (28, 'Webcam', 'Tech', 140);
insert into inventaries (id, name, category, quantity) values (29, 'Printer', 'Tech', 145);
insert into inventaries (id, name, category, quantity) values (30, 'Smartphone', 'Tech', 150);
insert into inventaries (id, name, category, quantity) values (31, 'Headphones', 'Tech', 155);
insert into inventaries (id, name, category, quantity) values (32, 'Laptop', 'Tech', 160);
insert into inventaries (id, name, category, quantity) values (33, 'External Hard Drive', 'Tech', 165);
insert into inventaries (id, name, category, quantity) values (34, 'Coffee Maker', 'Appliances', 170);
insert into inventaries (id, name, category, quantity) values (35, 'Water Bottle', 'Kitchenware', 175);
insert into inventaries (id, name, category, quantity) values (36, 'Router', 'Tech', 180);
insert into inventaries (id, name, category, quantity) values (37, 'Projector', 'Tech', 185);
insert into inventaries (id, name, category, quantity) values (38, 'Paper Ream', 'Stationery', 190);
insert into inventaries (id, name, category, quantity) values (39, 'Scanner', 'Tech', 195);
insert into inventaries (id, name, category, quantity) values (40, 'Mouse', 'Tech', 200);
insert into inventaries (id, name, category, quantity) values (41, 'Keyboard', 'Tech', 205);
insert into inventaries (id, name, category, quantity) values (42, 'Monitor', 'Tech', 210);
insert into inventaries (id, name, category, quantity) values (43, 'Desk Chair', 'Furniture', 215);
insert into inventaries (id, name, category, quantity) values (44, 'Notebook', 'Stationery', 220);
insert into inventaries (id, name, category, quantity) values (45, 'Tablet', 'Tech', 225);
insert into inventaries (id, name, category, quantity) values (46, 'Pen', 'Stationery', 230);
insert into inventaries (id, name, category, quantity) values (47, 'Desk Lamp', 'Furniture', 235);
insert into inventaries (id, name, category, quantity) values (48, 'Webcam', 'Tech', 240);
insert into inventaries (id, name, category, quantity) values (49, 'Printer', 'Tech', 245);
insert into inventaries (id, name, category, quantity) values (50, 'Smartphone', 'Tech', 250);
insert into inventaries (id, name, category, quantity) values (51, 'Headphones', 'Tech', 255);
insert into inventaries (id, name, category, quantity) values (52, 'Laptop', 'Tech', 260);
insert into inventaries (id, name, category, quantity) values (53, 'External Hard Drive', 'Tech', 265);
insert into inventaries (id, name, category, quantity) values (54, 'Coffee Maker', 'Appliances', 270);
insert into inventaries (id, name, category, quantity) values (55, 'Water Bottle', 'Kitchenware', 275);
insert into inventaries (id, name, category, quantity) values (56, 'Router', 'Tech', 280);
insert into inventaries (id, name, category, quantity) values (57, 'Projector', 'Tech', 285);
insert into inventaries (id, name, category, quantity) values (58, 'Paper Ream', 'Stationery', 290);
insert into inventaries (id, name, category, quantity) values (59, 'Scanner', 'Tech', 295);
insert into inventaries (id, name, category, quantity) values (60, 'Mouse', 'Tech', 300);
insert into inventaries (id, name, category, quantity) values (61, 'Keyboard', 'Tech', 305);
insert into inventaries (id, name, category, quantity) values (62, 'Monitor', 'Tech', 310);
insert into inventaries (id, name, category, quantity) values (63, 'Desk Chair', 'Furniture', 315);
insert into inventaries (id, name, category, quantity) values (64, 'Notebook', 'Stationery', 320);
insert into inventaries (id, name, category, quantity) values (65, 'Tablet', 'Tech', 325);
insert into inventaries (id, name, category, quantity) values (66, 'Pen', 'Stationery', 330);
insert into inventaries (id, name, category, quantity) values (67, 'Desk Lamp', 'Furniture', 335);
insert into inventaries (id, name, category, quantity) values (68, 'Webcam', 'Tech', 340);
insert into inventaries (id, name, category, quantity) values (69, 'Printer', 'Tech', 345);
insert into inventaries (id, name, category, quantity) values (70, 'Smartphone', 'Tech', 350);
insert into inventaries (id, name, category, quantity) values (71, 'Headphones', 'Tech', 355);
insert into inventaries (id, name, category, quantity) values (72, 'Laptop', 'Tech', 360);
insert into inventaries (id, name, category, quantity) values (73, 'External Hard Drive', 'Tech', 365);
insert into inventaries (id, name, category, quantity) values (74, 'Coffee Maker', 'Appliances', 370);
insert into inventaries (id, name, category, quantity) values (75, 'Water Bottle', 'Kitchenware', 375);
insert into inventaries (id, name, category, quantity) values (76, 'Router', 'Tech', 380);
insert into inventaries (id, name, category, quantity) values (77, 'Projector', 'Tech', 385);
insert into inventaries (id, name, category, quantity) values (78, 'Paper Ream', 'Stationery', 390);
insert into inventaries (id, name, category, quantity) values (79, 'Scanner', 'Tech', 395);
insert into inventaries (id, name, category, quantity) values (80, 'Mouse', 'Tech', 400);
insert into inventaries (id, name, category, quantity) values (81, 'Keyboard', 'Tech', 405);
insert into inventaries (id, name, category, quantity) values (82, 'Monitor', 'Tech', 410);
insert into inventaries (id, name, category, quantity) values (83, 'Desk Chair', 'Furniture', 415);
insert into inventaries (id, name, category, quantity) values (84, 'Notebook', 'Stationery', 420);
insert into inventaries (id, name, category, quantity) values (85, 'Tablet', 'Tech', 425);
insert into inventaries (id, name, category, quantity) values (86, 'Pen', 'Stationery', 430);
insert into inventaries (id, name, category, quantity) values (87, 'Desk Lamp', 'Furniture', 435);
insert into inventaries (id, name, category, quantity) values (88, 'Webcam', 'Tech', 440);
insert into inventaries (id, name, category, quantity) values (89, 'Printer', 'Tech', 445);
insert into inventaries (id, name, category, quantity) values (90, 'Smartphone', 'Tech', 450);
insert into inventaries (id, name, category, quantity) values (91, 'Headphones', 'Tech', 455);
insert into inventaries (id, name, category, quantity) values (92, 'Laptop', 'Tech', 460);
insert into inventaries (id, name, category, quantity) values (93, 'External Hard Drive', 'Tech', 465);
insert into inventaries (id, name, category, quantity) values (94, 'Coffee Maker', 'Appliances', 470);
insert into inventaries (id, name, category, quantity) values (95, 'Water Bottle', 'Kitchenware', 475);
insert into inventaries (id, name, category, quantity) values (96, 'Router', 'Tech', 480);
insert into inventaries (id, name, category, quantity) values (97, 'Projector', 'Tech', 485);
insert into inventaries (id, name, category, quantity) values (98, 'Paper Ream', 'Stationery', 490);
insert into inventaries (id, name, category, quantity) values (99, 'Scanner', 'Tech', 495);
insert into inventaries (id, name, category, quantity) values (100, 'Mouse', 'Tech', 500);
