
insert into categories (id, name) values (1, 'Tech');
insert into categories (id, name) values (2, 'Furniture');
insert into categories (id, name) values (3, 'Appliances');
insert into categories (id, name) values (4, 'Kitchenware');

insert into roles (id, name) values (1, 'Administrator');
insert into roles (id, name, category_id) values (2, 'Asesor Tech', 1);


insert into users (id, username, password) values(1, 'edwin', '123');
insert into users (id, username, password, role_id) values(2, 'andres', '123', 2);

insert into inventaries (id, name, category_id, quantity) values (1, 'Keyboard', 1, 5);
insert into inventaries (id, name, category_id, quantity) values (2, 'Monitor', 1, 10);
insert into inventaries (id, name, category_id, quantity) values (3, 'Desk Chair', 2, 15);
insert into inventaries (id, name, category_id, quantity) values (4, 'Notebook', 3, 20);
insert into inventaries (id, name, category_id, quantity) values (5, 'Tablet', 1, 25);
insert into inventaries (id, name, category_id, quantity) values (6, 'Pen', 3, 30);
insert into inventaries (id, name, category_id, quantity) values (7, 'Desk Lamp', 2, 35);
insert into inventaries (id, name, category_id, quantity) values (8, 'Webcam', 1, 40);
insert into inventaries (id, name, category_id, quantity) values (9, 'Printer', 1, 45);
insert into inventaries (id, name, category_id, quantity) values (10, 'Smartphone', 1, 50);
insert into inventaries (id, name, category_id, quantity) values (11, 'Headphones', 1, 55);
insert into inventaries (id, name, category_id, quantity) values (12, 'Laptop', 1, 60);
insert into inventaries (id, name, category_id, quantity) values (13, 'External Hard Drive', 1, 65);
insert into inventaries (id, name, category_id, quantity) values (14, 'Coffee Maker', 3, 70);
insert into inventaries (id, name, category_id, quantity) values (15, 'Water Bottle', 4, 75);
insert into inventaries (id, name, category_id, quantity) values (16, 'Router', 1, 80);
insert into inventaries (id, name, category_id, quantity) values (17, 'Projector', 1, 85);
insert into inventaries (id, name, category_id, quantity) values (18, 'Paper Ream', 3, 90);
insert into inventaries (id, name, category_id, quantity) values (19, 'Scanner', 1, 95);
insert into inventaries (id, name, category_id, quantity) values (20, 'Mouse', 1, 100);
insert into inventaries (id, name, category_id, quantity) values (21, 'Keyboard', 1, 105);
insert into inventaries (id, name, category_id, quantity) values (22, 'Monitor', 1, 110);
insert into inventaries (id, name, category_id, quantity) values (23, 'Desk Chair', 2, 115);
insert into inventaries (id, name, category_id, quantity) values (24, 'Notebook', 3, 120);
insert into inventaries (id, name, category_id, quantity) values (25, 'Tablet', 1, 125);
insert into inventaries (id, name, category_id, quantity) values (26, 'Pen', 3, 130);
insert into inventaries (id, name, category_id, quantity) values (27, 'Desk Lamp', 2, 135);
insert into inventaries (id, name, category_id, quantity) values (28, 'Webcam', 1, 140);
insert into inventaries (id, name, category_id, quantity) values (29, 'Printer', 1, 145);
insert into inventaries (id, name, category_id, quantity) values (30, 'Smartphone', 1, 150);
insert into inventaries (id, name, category_id, quantity) values (31, 'Headphones', 1, 155);
insert into inventaries (id, name, category_id, quantity) values (32, 'Laptop', 1, 160);
insert into inventaries (id, name, category_id, quantity) values (33, 'External Hard Drive', 1, 165);
insert into inventaries (id, name, category_id, quantity) values (34, 'Coffee Maker', 3, 170);
insert into inventaries (id, name, category_id, quantity) values (35, 'Water Bottle', 4, 175);
insert into inventaries (id, name, category_id, quantity) values (36, 'Router', 1, 180);
insert into inventaries (id, name, category_id, quantity) values (37, 'Projector', 1, 185);
insert into inventaries (id, name, category_id, quantity) values (38, 'Paper Ream', 3, 190);
insert into inventaries (id, name, category_id, quantity) values (39, 'Scanner', 1, 195);
insert into inventaries (id, name, category_id, quantity) values (40, 'Mouse', 1, 200);
insert into inventaries (id, name, category_id, quantity) values (41, 'Keyboard', 1, 205);
insert into inventaries (id, name, category_id, quantity) values (42, 'Monitor', 1, 210);
insert into inventaries (id, name, category_id, quantity) values (43, 'Desk Chair', 2, 215);
insert into inventaries (id, name, category_id, quantity) values (44, 'Notebook', 3, 220);
insert into inventaries (id, name, category_id, quantity) values (45, 'Tablet', 1, 225);
insert into inventaries (id, name, category_id, quantity) values (46, 'Pen', 3, 230);
insert into inventaries (id, name, category_id, quantity) values (47, 'Desk Lamp', 2, 235);
insert into inventaries (id, name, category_id, quantity) values (48, 'Webcam', 1, 240);
insert into inventaries (id, name, category_id, quantity) values (49, 'Printer', 1, 245);
insert into inventaries (id, name, category_id, quantity) values (50, 'Smartphone', 1, 250);
insert into inventaries (id, name, category_id, quantity) values (51, 'Headphones', 1, 255);
insert into inventaries (id, name, category_id, quantity) values (52, 'Laptop', 1, 260);
insert into inventaries (id, name, category_id, quantity) values (53, 'External Hard Drive', 1, 265);
insert into inventaries (id, name, category_id, quantity) values (54, 'Coffee Maker', 3, 270);
insert into inventaries (id, name, category_id, quantity) values (55, 'Water Bottle', 4, 275);
insert into inventaries (id, name, category_id, quantity) values (56, 'Router', 1, 280);
insert into inventaries (id, name, category_id, quantity) values (57, 'Projector', 1, 285);
insert into inventaries (id, name, category_id, quantity) values (58, 'Paper Ream', 3, 290);
insert into inventaries (id, name, category_id, quantity) values (59, 'Scanner', 1, 295);
insert into inventaries (id, name, category_id, quantity) values (60, 'Mouse', 1, 300);
insert into inventaries (id, name, category_id, quantity) values (61, 'Keyboard', 1, 305);
insert into inventaries (id, name, category_id, quantity) values (62, 'Monitor', 1, 310);
insert into inventaries (id, name, category_id, quantity) values (63, 'Desk Chair', 2, 315);
insert into inventaries (id, name, category_id, quantity) values (64, 'Notebook', 3, 320);
insert into inventaries (id, name, category_id, quantity) values (65, 'Tablet', 1, 325);
insert into inventaries (id, name, category_id, quantity) values (66, 'Pen', 3, 330);
insert into inventaries (id, name, category_id, quantity) values (67, 'Desk Lamp', 2, 335);
insert into inventaries (id, name, category_id, quantity) values (68, 'Webcam', 1, 340);
insert into inventaries (id, name, category_id, quantity) values (69, 'Printer', 1, 345);
insert into inventaries (id, name, category_id, quantity) values (70, 'Smartphone', 1, 350);
insert into inventaries (id, name, category_id, quantity) values (71, 'Headphones', 1, 355);
insert into inventaries (id, name, category_id, quantity) values (72, 'Laptop', 1, 360);
insert into inventaries (id, name, category_id, quantity) values (73, 'External Hard Drive', 1, 365);
insert into inventaries (id, name, category_id, quantity) values (74, 'Coffee Maker', 3, 370);
insert into inventaries (id, name, category_id, quantity) values (75, 'Water Bottle', 4, 375);
insert into inventaries (id, name, category_id, quantity) values (76, 'Router', 1, 380);
insert into inventaries (id, name, category_id, quantity) values (77, 'Projector', 1, 385);
insert into inventaries (id, name, category_id, quantity) values (78, 'Paper Ream', 3, 390);
insert into inventaries (id, name, category_id, quantity) values (79, 'Scanner', 1, 395);
insert into inventaries (id, name, category_id, quantity) values (80, 'Mouse', 1, 400);
insert into inventaries (id, name, category_id, quantity) values (81, 'Keyboard', 1, 405);
insert into inventaries (id, name, category_id, quantity) values (82, 'Monitor', 1, 410);
insert into inventaries (id, name, category_id, quantity) values (83, 'Desk Chair', 2, 415);
insert into inventaries (id, name, category_id, quantity) values (84, 'Notebook', 3, 420);
insert into inventaries (id, name, category_id, quantity) values (85, 'Tablet', 1, 425);
insert into inventaries (id, name, category_id, quantity) values (86, 'Pen', 3, 430);
insert into inventaries (id, name, category_id, quantity) values (87, 'Desk Lamp', 2, 435);
insert into inventaries (id, name, category_id, quantity) values (88, 'Webcam', 1, 440);
insert into inventaries (id, name, category_id, quantity) values (89, 'Printer', 1, 445);
insert into inventaries (id, name, category_id, quantity) values (90, 'Smartphone', 1, 450);
insert into inventaries (id, name, category_id, quantity) values (91, 'Headphones', 1, 455);
insert into inventaries (id, name, category_id, quantity) values (92, 'Laptop', 1, 460);
insert into inventaries (id, name, category_id, quantity) values (93, 'External Hard Drive', 1, 465);
insert into inventaries (id, name, category_id, quantity) values (94, 'Coffee Maker', 3, 470);
insert into inventaries (id, name, category_id, quantity) values (95, 'Water Bottle', 4, 475);
insert into inventaries (id, name, category_id, quantity) values (96, 'Router', 1, 480);
insert into inventaries (id, name, category_id, quantity) values (97, 'Projector', 1, 485);
insert into inventaries (id, name, category_id, quantity) values (98, 'Paper Ream', 3, 490);
insert into inventaries (id, name, category_id, quantity) values (99, 'Scanner', 1, 495);
insert into inventaries (id, name, category_id, quantity) values (100, 'Mouse', 1, 500);
